---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: partybuzz-ch
  namespace: default
spec:
  secretName: partybuzz-ch-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "partybuzz.ch"
  dnsNames:
    - "partybuzz.ch"