#cloud-config
users:
  - name: pb
    sudo: ['ALL=(ALL) NOPASSWD:ALL']¥
    ssh_pwauth: True
    lock_passwd: False
    passwd: $6$xyz$gdKBYbzggYolytjUecIWA42mK.OUQOkK1iS7gmLZ.XhpFgMwHkBO7jyHOOoWvEehE.txp8F3z6OGLezB43Y1q1
chpasswd: { expire: False }