#cloud-config
users:
  - name: pb
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_pwauth: True
    lock_passwd: False
    passwd: ZvippUlBOu8NYHm9bnu/svUn4NTyQCbQvd4mRDyId8HwDCbgwXSEWE35OQZY66XSNyJjlMtNp0NmXSZeOUPgt0
chpasswd: { expire: False }