- name: Download Helm binary
  get_url:
    url: "{{ helm_download_url }}"
    dest: "/tmp/helm.tar.gz"

- name: Extract Helm binary
  unarchive:
    src: "/tmp/helm.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Move Helm binary
  command: "sudo mv /tmp/{{ helm_architecture }}/helm /usr/local/bin/helm"

- name: Verify Helm installation
  command: "helm version"