---

- name: Ensure dependencies are installed
  pip:
    name: kubernetes
    state: present

- name: Install k3s on first server
  shell: >
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - server \
    --token={{ k3s_token }} \
    --tls-san {{ dns_name }} --tls-san {{ lb_ip_address }} \
    --cluster-init
  when: inventory_hostname == groups['masters'][0]

- name: Ensure .kube directory exists
  file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: inventory_hostname == groups['masters'][0]

- name: Copy k3s kubeconfig to local directory for the first master
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == groups['masters'][0]

- name: Install helm
  include_tasks: helm.yaml
  when: inventory_hostname == groups['masters'][0]

- name: Install traefik
  include_tasks: traefik.yaml
  when: inventory_hostname == groups['masters'][0]

- name: Get IP of the first server
  set_fact:
    first_server_ip: "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}"
  run_once: true

- name: Install k3s on the remaining masters
  shell: >
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - server \
    --token={{ k3s_token }} \
    --tls-san {{ dns_name }} --tls-san {{ lb_ip_address }} \
    --server https://{{ first_server_ip }}:6443
  when: inventory_hostname != groups['masters'][0]
