- name: Copy a file to the target host
  copy:
    src:  ../templates/values.yaml
    dest: ~/values.yaml

- name: Add Traefik Helm repository
  command:
    cmd: helm repo add traefik https://traefik.github.io/charts

- name: Update Helm repos
  command:
    cmd: helm repo update

- name: Install Traefik Helm chart
  command:
    cmd: helm install --namespace=traefik traefik traefik/traefik --values=values.yaml