---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: "MEwyTU5LM2l3UjBXaGZNVDEwMUN5RFltdkRoZmNYME9QcjY2Uzl2Mg=="